# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate Latent Channel Network
#' @param p_mat Matrix of channel usage probabilities
#' @export
simLCN <- function(p_mat) {
    .Call('_latChanNet_simLCN', PACKAGE = 'latChanNet', p_mat)
}

