# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predict_lat_edges <- function(r_i, r_j, pmat, model) {
    .Call('_latChanNet_predict_lat_edges', PACKAGE = 'latChanNet', r_i, r_j, pmat, model)
}

predict_crossedge <- function(r_i, r_j, pmat, model) {
    .Call('_latChanNet_predict_crossedge', PACKAGE = 'latChanNet', r_i, r_j, pmat, model)
}

chanConnect <- function(r_i, r_j, pmat, model) {
    .Call('_latChanNet_chanConnect', PACKAGE = 'latChanNet', r_i, r_j, pmat, model)
}

#' Simulate Latent Channel Network
#' @param p_mat Matrix of channel usage probabilities
#' @export
simLCN <- function(p_mat) {
    .Call('_latChanNet_simLCN', PACKAGE = 'latChanNet', p_mat)
}

