---
title: "SBM Plots"
author: "Clifford Anderson-Bergman"
date: "5/11/2019"
output: html_document
---

```{r}
library(latChanNet)
library(igraph)
library(grid)
library(ggplot2)

set.seed(123)

# Function for saving pheatmaps
save_pheatmap_pdf <- function(x, filename, width=7, height=7) {
   stopifnot(!missing(x))
   stopifnot(!missing(filename))
   pdf(filename, width=width, height=height)
   grid::grid.newpage()
   grid::grid.draw(x$gtable)
   dev.off()
}

## Sampling SBM
p_in = 0.25
p_out = 0.025
nGrp = 10
nPerGrp = 100
block_membership = rep(1:nGrp, each = nPerGrp)
# Constructing probability matrix
p_mat = matrix(p_out, nrow = nGrp, ncol = nGrp)
diag(p_mat) = p_in
# Sampling
sbm1 = sample_sbm(nGrp * nPerGrp, p_mat, rep(nPerGrp, nGrp) )
sbm1_edgeList = as_edgelist(sbm1)

# Fitting
mod1 = makeLCN(sbm1_edgeList, nGrp)
emLCN(mod1, iters = 10000)
# Plotting
heatmapLCN(mod1, grp = block_membership, 
           xlab = "Nodes", 
           ylab = "Channels", 
           main = "Channel Usage by Node for Stochastic Block Model")
ggsave("baseSBM.pdf")
```

```{r}

# Constructing probability matrix
p_mat = matrix(p_out, nrow = nGrp, ncol = nGrp)
diag(p_mat) = p_in


## Sampling SBM with highly connected block
p_mat_aug = cbind(p_mat, p_in)
p_mat_aug = rbind(p_mat_aug, p_in)
block_membership = c(block_membership, 
                     rep(nGrp + 1, nPerGrp))
sbm2 = sample_sbm( (nGrp + 1) * nPerGrp, 
                   p_mat_aug, 
                   rep(nPerGrp, nGrp + 1) )
sbm2_edgeList = as_edgelist(sbm2)


# Fitting
mod2 = makeLCN(sbm2_edgeList, nGrp)
emLCN(mod2, iters = 10000)
# Plotting
heatmapLCN(mod2, grp = block_membership, 
           xlab = "Nodes", 
           ylab = "Channels", 
           main = 
            "Channel Frequency by Node for Stochastic Block Model")

pdf("augSBM.pdf")
heatmapLCN(mod2, grp = block_membership, 
              xlab = "Nodes", 
              ylab = "Channels", 
              main = 
                "Channel Frequency by Node for Stochastic Block Model", 
           filename = "augSBM.pdf")

graphics.off()
```

